@startuml

title __BARCODE's Class Diagram__\n

  package ca.rededaniskal {
    package ca.rededaniskal.Barcode {
      class Barcode_Fragment {
          {static} - TAG : String
          {static} + newInstance()
          + onCreate()
          + onCreateView()
          + onScanned()
          + onScannedMultiple()
          + onBitmapScanned()
          + onScanError()
          + onCameraPermissionDenied()
      }
    }
  }
  

  package ca.rededaniskal {
    package ca.rededaniskal.Barcode {
      class Barcode_Graphic {
          - mId : int
          {static} - COLOR_CHOICES : int[]
          {static} - mCurrentColorIndex : int
          - mRectPaint : Paint
          - mTextPaint : Paint
          - mBarcode : Barcode
          ~ Barcode_Graphic()
          + getId()
          + setId()
          + getBarcode()
          ~ updateItem()
          + draw()
      }
    }
  }
  

  package ca.rededaniskal {
    package ca.rededaniskal.Barcode {
      class Barcode_Graphic_Tracker {
          - mOverlay : GraphicOverlay<Barcode_Graphic>
          ~ Barcode_Graphic_Tracker()
          + onNewItem()
          + onUpdate()
          {static} + asList()
          + onMissing()
          + onDone()
      }
    }
  }
  

  package ca.rededaniskal {
    package ca.rededaniskal.Barcode {
      interface BarcodeGraphicTrackerListener {
          {abstract} + onScanned()
          {abstract} + onScannedMultiple()
          {abstract} + onBitmapScanned()
          {abstract} + onScanError()
      }
    }
  }
  

  package ca.rededaniskal {
    package ca.rededaniskal.Barcode {
      class Barcode_Reader_Activity {
          {static} + KEY_CAPTURED_BARCODE : String
          {static} + KEY_CAPTURED_RAW_BARCODE : String
          {static} - KEY_AUTO_FOCUS : String
          {static} - KEY_USE_FLASH : String
          - autoFocus : boolean
          - useFlash : boolean
          # onCreate()
          - attachBarcodeReaderFragment()
          {static} + getLaunchIntent()
          + onScanned()
          + onScannedMultiple()
          + onBitmapScanned()
          + onScanError()
          + onCameraPermissionDenied()
      }
    }
  }
  

  package ca.rededaniskal {
    package ca.rededaniskal.Barcode {
      class Barcode_Reader_Fragment {
          {static} # TAG : String
          {static} # KEY_AUTO_FOCUS : String
          {static} # KEY_USE_FLASH : String
          {static} - KEY_SCAN_OVERLAY_VISIBILITY : String
          {static} - RC_HANDLE_GMS : int
          # autoFocus : boolean
          # useFlash : boolean
          - beepSoundFile : String
          {static} + BarcodeObject : String
          - isPaused : boolean
          - mGraphicOverlay : GraphicOverlay<Barcode_Graphic>
          - scaleGestureDetector : ScaleGestureDetector
          - gestureDetector : GestureDetector
          - permissionStatus : SharedPreferences
          {static} - PERMISSION_CALLBACK_CONSTANT : int
          {static} - REQUEST_PERMISSION_SETTING : int
          - sentToSettings : boolean
          - scanOverlayVisibility : int
          + Barcode_Reader_Fragment()
          {static} + newInstance()
          {static} + newInstance()
          + setListener()
          + setBeepSoundFile()
          + pauseScanning()
          + resumeScanning()
          + onCreate()
          + onCreateView()
          + onInflate()
          + onAttach()
          + onActivityCreated()
          - proceedAfterPermission()
          - createCameraSource()
          + setUseFlash()
          + setAutoFocus()
          + deviceSupportsFlash()
          + onResume()
          + onPause()
          + onDestroy()
          + onRequestPermissionsResult()
          + onActivityResult()
          - startCameraSource()
          - onTap()
          + onTouch()
          + onScanned()
          + onScannedMultiple()
          + onBitmapScanned()
          + onScanError()
          + playBeep()
      }
    }
  }
  

  package ca.rededaniskal {
    package ca.rededaniskal.Barcode {
      class CaptureGestureListener {
          + onSingleTapConfirmed()
      }
    }
  }
  

  package ca.rededaniskal {
    package ca.rededaniskal.Barcode {
      class ScaleListener {
          + onScale()
          + onScaleBegin()
          + onScaleEnd()
      }
    }
  }
  

  package ca.rededaniskal {
    package ca.rededaniskal.Barcode {
      interface BarcodeReaderListener {
          {abstract} + onScanned()
          {abstract} + onScannedMultiple()
          {abstract} + onBitmapScanned()
          {abstract} + onScanError()
          {abstract} + onCameraPermissionDenied()
      }
    }
  }
  

  package ca.rededaniskal {
    package ca.rededaniskal.Barcode {
      class Barcode_Scanner_Activity {
          - mTvResult : TextView
          # onCreate()
          - addBarcodeReaderFragment()
          + onClick()
          # onActivityResult()
          + onScanned()
          + onScannedMultiple()
          + onBitmapScanned()
          + onScanError()
          + onCameraPermissionDenied()
      }
    }
  }
  

  package ca.rededaniskal {
    package ca.rededaniskal.Barcode {
      class Barcode_Tracker_Factory {
          - mGraphicOverlay : GraphicOverlay<Barcode_Graphic>
          ~ Barcode_Tracker_Factory()
          + create()
      }
    }
  }
  

  package ca.rededaniskal {
    package ca.rededaniskal.Barcode {
      class Scanner_Overlay {
          - left : float
          - top : float
          - endY : float
          - rectWidth : int
          - rectHeight : int
          - frames : int
          - revAnimation : boolean
          - lineColor : int
          - lineWidth : int
          + Scanner_Overlay()
          + Scanner_Overlay()
          + Scanner_Overlay()
          # onMeasure()
          + onLayout()
          # onSizeChanged()
          + dpToPx()
          + shouldDelayChildPressedState()
          # dispatchDraw()
          # onDraw()
      }
    }
  }
  

  Barcode_Fragment -up-|> BarcodeReaderListener
  Barcode_Fragment -up-|> Fragment
  Barcode_Fragment o-- Barcode_Reader_Fragment : barcodeReader
  SavedState -up-|> Parcelable
  Barcode_Graphic -up-|> Graphic
  Barcode_Graphic_Tracker -up-|> Tracker
  Barcode_Graphic_Tracker o-- Barcode_Graphic : mGraphic
  Barcode_Graphic_Tracker o-- BarcodeGraphicTrackerListener : listener
  Barcode_Graphic_Tracker +-down- BarcodeGraphicTrackerListener
  Barcode_Reader_Activity -up-|> BarcodeReaderListener
  Barcode_Reader_Activity -up-|> AppCompatActivity
  Barcode_Reader_Activity o-- Barcode_Reader_Fragment : mBarcodeReaderFragment
  HostCallbacks -up-|> FragmentHostCallback
  Barcode_Reader_Fragment -up-|> OnTouchListener
  Barcode_Reader_Fragment -up-|> BarcodeGraphicTrackerListener
  Barcode_Reader_Fragment -up-|> Fragment
  Barcode_Reader_Fragment o-- CameraSource : mCameraSource
  Barcode_Reader_Fragment o-- CameraSourcePreview : mPreview
  Barcode_Reader_Fragment o-- BarcodeReaderListener : mListener
  Barcode_Reader_Fragment o-- Scanner_Overlay : mScanOverlay
  Barcode_Reader_Fragment +-down- CaptureGestureListener
  Barcode_Reader_Fragment +-down- ScaleListener
  Barcode_Reader_Fragment +-down- BarcodeReaderListener
  CaptureGestureListener -up-|> SimpleOnGestureListener
  ScaleListener -up-|> OnScaleGestureListener
  SavedState -up-|> Parcelable
  Barcode_Scanner_Activity -up-|> OnClickListener
  Barcode_Scanner_Activity -up-|> BarcodeReaderListener
  Barcode_Scanner_Activity -up-|> AppCompatActivity
  HostCallbacks -up-|> FragmentHostCallback
  Barcode_Tracker_Factory -up-|> Factory
  Barcode_Tracker_Factory o-- BarcodeGraphicTrackerListener : listener
  Scanner_Overlay -up-|> ViewGroup
  MarginLayoutParams -up-|> LayoutParams
  BaseSavedState -up-|> AbsSavedState


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
