@startuml

title __REDEDANISKAL's Class Diagram__\n

  package ca.rededaniskal {
    class AddBookToLibraryTest {
        - solo : Solo
        + rule : ActivityTestRule<Add_Book_To_Library_Activity>
        + AddBookToLibraryTest()
        + setUp()
        + start()
        + addBookToLibrary()
    }
  }
  

  package ca.rededaniskal {
    class AlertTest {
        - solo : Solo
        + rule : ActivityTestRule<Main_Activity>
        + AlertTest()
        + setUp()
        + start()
    }
  }
  

  package ca.rededaniskal {
    class AllRequestsTest {
        - solo : Solo
        + rule : ActivityTestRule<View_All_Requests_Activity>
        + AllRequestsTest()
        + setUp()
        + start()
    }
  }
  

  package ca.rededaniskal {
    class BorrowRequestBookTest {
        - solo : Solo
        + rule : ActivityTestRule<View_Borrowed_Requested_Activity>
        + BorrowRequestBookTest()
        + setUp()
        + start()
        + openBook()
    }
  }
  

  package ca.rededaniskal {
    class EditBookDetailsTest {
        - solo : Solo
        + rule : ActivityTestRule<Edit_Book_Instance_Activity>
        + EditBookDetailsTest()
        + setUp()
        + start()
        + editDetailsTest()
        + deleteBook()
    }
  }
  

  package ca.rededaniskal {
    class EditProfileTest {
        - solo : Solo
        + rule : ActivityTestRule<Edit_Profile_Activity>
        + EditProfileTest()
        + setUp()
        + start()
        + TestEdit()
    }
  }
  

  package ca.rededaniskal {
    class ExampleInstrumentedTest {
        + useAppContext()
    }
  }
  

  package ca.rededaniskal {
    class FeedTest {
        - solo : Solo
        + rule : ActivityTestRule<Main_Activity>
        + FeedTest()
        + setUp()
        + start()
        + TestFeed()
    }
  }
  

  package ca.rededaniskal {
    class FriendListTest {
        - solo : Solo
        + rule : ActivityTestRule<View_Friends_Activity>
        + FriendListTest()
        + setUp()
        + start()
        + checkFriend()
    }
  }
  

  package ca.rededaniskal {
    class LibraryTest {
        - solo : Solo
        + rule : ActivityTestRule<View_My_Library_Activity>
        + LibraryTest()
        + setUp()
        + start()
        + addBookToLibrary()
        + checkBook()
    }
  }
  

  package ca.rededaniskal {
    class LoginTest {
        - solo : Solo
        + rule : ActivityTestRule<Login_Activity>
        + LoginTest()
        + setUp()
        + start()
        + testLogin()
        + testFailedLogin()
        + goToSignup()
    }
  }
  

  package ca.rededaniskal {
    class ProfileTest {
        - solo : Solo
        + rule : ActivityTestRule<Main_Activity>
        + ProfileTest()
        + setUp()
        + start()
        + TestEditProfile()
        + TestFriendList()
        + TestBorrowRequestBooks()
        + TestAllBookRequests()
        + TestLibrary()
    }
  }
  

  package ca.rededaniskal {
    class SignupTest {
        - solo : Solo
        + rule : ActivityTestRule<Signup_Activity>
        + SignupTest()
        + setUp()
        + start()
        + checkDuplicateSignup()
        + checkSignup()
    }
  }
  

  AddBookToLibraryTest -up-|> ActivityTestRule
  LifecycleCallback -up-|> ActivityLifecycleCallback
  ActivityStatement -up-|> Statement
  AlertTest -up-|> ActivityTestRule
  LifecycleCallback -up-|> ActivityLifecycleCallback
  ActivityStatement -up-|> Statement
  AllRequestsTest -up-|> ActivityTestRule
  LifecycleCallback -up-|> ActivityLifecycleCallback
  ActivityStatement -up-|> Statement
  BorrowRequestBookTest -up-|> ActivityTestRule
  LifecycleCallback -up-|> ActivityLifecycleCallback
  ActivityStatement -up-|> Statement
  EditBookDetailsTest -up-|> ActivityTestRule
  LifecycleCallback -up-|> ActivityLifecycleCallback
  ActivityStatement -up-|> Statement
  EditProfileTest -up-|> ActivityTestRule
  LifecycleCallback -up-|> ActivityLifecycleCallback
  ActivityStatement -up-|> Statement
  FeedTest -up-|> ActivityTestRule
  LifecycleCallback -up-|> ActivityLifecycleCallback
  ActivityStatement -up-|> Statement
  FriendListTest -up-|> ActivityTestRule
  LifecycleCallback -up-|> ActivityLifecycleCallback
  ActivityStatement -up-|> Statement
  LibraryTest -up-|> ActivityTestRule
  LifecycleCallback -up-|> ActivityLifecycleCallback
  ActivityStatement -up-|> Statement
  LoginTest -up-|> ActivityTestRule
  LifecycleCallback -up-|> ActivityLifecycleCallback
  ActivityStatement -up-|> Statement
  ProfileTest -up-|> ActivityTestRule
  LifecycleCallback -up-|> ActivityLifecycleCallback
  ActivityStatement -up-|> Statement
  SignupTest -up-|> ActivityTestRule
  LifecycleCallback -up-|> ActivityLifecycleCallback
  ActivityStatement -up-|> Statement


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
