@startuml

title __REDEDANISKAL's Class Diagram__\n

  package ca.rededaniskal {
    class BookInstanceTest {
        + TestTitle()
        + TestAuthor()
        + TestISBN()
        + TestDescription()
        + TestStatus()
        + TestOwner()
        + TestBorrower()
        + TestBookID()
    }
  }
  

  package ca.rededaniskal {
    class BookListTests {
        + addBook()
        + removeBook()
        + getBookByIndex()
        + getBooks()
        + getBooksByStatus()
        + size()
        + clear()
    }
  }
  

  package ca.rededaniskal {
    class BookNotificationTest {
        + requestType()
        + setMessage()
    }
  }
  

  package ca.rededaniskal {
    class ForumTest {
        + AddPost()
        + DeletePost()
        + TestForumID()
    }
  }
  

  package ca.rededaniskal {
    class FriendNotificationTest {
        + requestType()
        + setMessage()
    }
  }
  

  package ca.rededaniskal {
    class NotificationTest {
        + Timestamp()
        + Username()
        + Request()
    }
  }
  

  package ca.rededaniskal {
    class RequestTest {
        + getUsernames()
        + setUsernames()
        + testRequestType()
        + getStatus()
        + setStatus()
        + Accept()
        + Deny()
        + Cancel()
        + testRequestId()
        + testISBN()
        + testBookId()
    }
  }
  

  package ca.rededaniskal {
    class UserUnitTest {
        + getFavBook()
        + setFavBook()
        + getRequestedBooks()
        + setRequestedBooks()
        + getUserName()
        + setUserName()
        + getEmail()
        + setEmail()
        + getPhoneNumber()
        + setPhoneNumber()
        + getLocation()
        + setLocation()
        + getFriends()
        + setFriends()
        + getOwnedBooks()
        + setOwnedBooks()
        + getBorrowedBooks()
        + setBorrowedBooks()
        + getBlockedUsers()
        + setBlockedUsers()
        + addRequestedBook()
        + deleteRequestedBook()
        + addOwnedBook()
        + deleteOwnedBook()
        + removeAllOwnedBooks()
        + addFriend()
        + removeFriend()
        + removeAllFriends()
        + addBlockedUser()
        + removeBlockedUser()
        + deleteProfile()
        - allBooksReturned()
        + addBorrowedBook()
        + deleteBorrowedBook()
        - giveRating()
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
