@startuml

title __APP's Class Diagram__\n

  package ca.rededaniskal {
    package ca.rededaniskal.Database {
      class AddBookDb {
      }
    }
  }
  

  package ca.rededaniskal {
    package ca.rededaniskal.BusinessLogic {
      class AddBookLogic {
      }
    }
  }
  

  package ca.rededaniskal {
    class AddBookToLibraryTest {
    }
  }
  

  package ca.rededaniskal {
    package ca.rededaniskal.Activities {
      class Add_Book_To_Library_Activity {
      }
    }
  }
  

  package ca.rededaniskal {
    class AlertTest {
    }
  }
  

  package ca.rededaniskal {
    package ca.rededaniskal.BusinessLogic {
      class AllRequestsAdapter {
      }
    }
  }
  

  package ca.rededaniskal {
    class AllRequestsTest {
    }
  }
  

  package ca.rededaniskal {
    package ca.rededaniskal.Barcode {
      class Barcode_Fragment {
      }
    }
  }
  

  package ca.rededaniskal {
    package ca.rededaniskal.Barcode {
      class Barcode_Graphic {
      }
    }
  }
  

  package ca.rededaniskal {
    package ca.rededaniskal.Barcode {
      class Barcode_Graphic_Tracker {
      }
    }
  }
  

  package ca.rededaniskal {
    package ca.rededaniskal.Barcode {
      class Barcode_Reader_Activity {
      }
    }
  }
  

  package ca.rededaniskal {
    package ca.rededaniskal.Barcode {
      class Barcode_Reader_Fragment {
      }
    }
  }
  

  package ca.rededaniskal {
    package ca.rededaniskal.Barcode {
      class Barcode_Scanner_Activity {
      }
    }
  }
  

  package ca.rededaniskal {
    package ca.rededaniskal.Barcode {
      class Barcode_Tracker_Factory {
      }
    }
  }
  

  package ca.rededaniskal {
    package ca.rededaniskal.EntityClasses {
      class Book {
      }
    }
  }
  

  package ca.rededaniskal {
    package ca.rededaniskal.BusinessLogic {
      class BookAdapter {
      }
    }
  }
  

  package ca.rededaniskal {
    package ca.rededaniskal.EntityClasses {
      class BookID {
      }
    }
  }
  

  package ca.rededaniskal {
    package ca.rededaniskal.Activities {
      class Book_Details_Activity {
      }
    }
  }
  

  package ca.rededaniskal {
    package ca.rededaniskal.EntityClasses {
      abstract class Book_Exchange {
      }
    }
  }
  

  package ca.rededaniskal {
    package ca.rededaniskal.EntityClasses {
      class Book_Instance {
      }
    }
  }
  

  package ca.rededaniskal {
    package ca.rededaniskal.EntityClasses {
      class Book_List {
      }
    }
  }
  

  package ca.rededaniskal {
    package ca.rededaniskal.EntityClasses {
      class BorrowRequest {
      }
    }
  }
  

  package ca.rededaniskal {
    package ca.rededaniskal.BusinessLogic {
      class BorrowRequestAdapter {
      }
    }
  }
  

  package ca.rededaniskal {
    class BorrowRequestBookTest {
    }
  }
  

  package ca.rededaniskal {
    class BuildConfig {
    }
  }
  

  package ca.rededaniskal {
    package ca.rededaniskal.Barcode {
      package ca.rededaniskal.Barcode.camera {
        class CameraSource {
        }
      }
    }
  }
  

  package ca.rededaniskal {
    package ca.rededaniskal.Barcode {
      package ca.rededaniskal.Barcode.camera {
        class CameraSourcePreview {
        }
      }
    }
  }
  

  package ca.rededaniskal {
    package ca.rededaniskal.EntityClasses {
      class Check_In {
      }
    }
  }
  

  package ca.rededaniskal {
    package ca.rededaniskal.EntityClasses {
      class Check_Out {
      }
    }
  }
  

  package ca.rededaniskal {
    package ca.rededaniskal.Database {
      class Data_Map {
      }
    }
  }
  

  package ca.rededaniskal {
    package ca.rededaniskal.Database {
      class Data_Provider {
      }
    }
  }
  

  package ca.rededaniskal {
    class EditBookDetailsTest {
    }
  }
  

  package ca.rededaniskal {
    class EditProfileTest {
    }
  }
  

  package ca.rededaniskal {
    package ca.rededaniskal.Activities {
      class Edit_Book_Instance_Activity {
      }
    }
  }
  

  package ca.rededaniskal {
    package ca.rededaniskal.Activities {
      class Edit_Profile_Activity {
      }
    }
  }
  

  package ca.rededaniskal {
    class ExampleInstrumentedTest {
    }
  }
  

  package ca.rededaniskal {
    class FeedTest {
    }
  }
  

  package ca.rededaniskal {
    package ca.rededaniskal.EntityClasses {
      class Forum {
      }
    }
  }
  

  package ca.rededaniskal {
    class FriendListTest {
    }
  }
  

  package ca.rededaniskal {
    package ca.rededaniskal.EntityClasses {
      class Friend_Request {
      }
    }
  }
  

  package ca.rededaniskal {
    package ca.rededaniskal.Database {
      class Get_All_Books_Data {
      }
    }
  }
  

  package ca.rededaniskal {
    package ca.rededaniskal.Barcode {
      package ca.rededaniskal.Barcode.camera {
        class GraphicOverlay {
        }
      }
    }
  }
  

  package ca.rededaniskal {
    package ca.rededaniskal.Activities {
      class Launcher_Activity {
      }
    }
  }
  

  package ca.rededaniskal {
    class LibraryTest {
    }
  }
  

  package ca.rededaniskal {
    package ca.rededaniskal.BusinessLogic {
      class Load_ALL_Books_Business {
      }
    }
  }
  

  package ca.rededaniskal {
    package ca.rededaniskal.BusinessLogic {
      class Log_In_Logic {
      }
    }
  }
  

  package ca.rededaniskal {
    class LoginTest {
    }
  }
  

  package ca.rededaniskal {
    package ca.rededaniskal.Activities {
      class Login_Activity {
      }
    }
  }
  

  package ca.rededaniskal {
    package ca.rededaniskal.Activities {
      class Main_Activity {
      }
    }
  }
  

  package ca.rededaniskal {
    package ca.rededaniskal.EntityClasses {
      class Master_Book {
      }
    }
  }
  

  package ca.rededaniskal {
    package ca.rededaniskal.EntityClasses {
      class Notification {
      }
    }
  }
  

  package ca.rededaniskal {
    package ca.rededaniskal.BusinessLogic {
      class Notification_Adapter {
      }
    }
  }
  

  package ca.rededaniskal {
    package ca.rededaniskal.Activities {
      package ca.rededaniskal.Activities.Fragments {
        class Notifications_Fragment {
        }
      }
    }
  }
  

  package ca.rededaniskal {
    package ca.rededaniskal.EntityClasses {
      class Post {
      }
    }
  }
  

  package ca.rededaniskal {
    package ca.rededaniskal.BusinessLogic {
      class PostAdapter {
      }
    }
  }
  

  package ca.rededaniskal {
    package ca.rededaniskal.Activities {
      package ca.rededaniskal.Activities.Fragments {
        class Post_Feed_Fragment {
        }
      }
    }
  }
  

  package ca.rededaniskal {
    class ProfileTest {
    }
  }
  

  package ca.rededaniskal {
    package ca.rededaniskal.EntityClasses {
      class Rating_Post {
      }
    }
  }
  

  package ca.rededaniskal {
    package ca.rededaniskal.EntityClasses {
      class Request {
      }
    }
  }
  

  package ca.rededaniskal {
    package ca.rededaniskal.Barcode {
      class Scanner_Overlay {
      }
    }
  }
  

  package ca.rededaniskal {
    package ca.rededaniskal.Activities {
      class Search_Activity {
      }
    }
  }
  

  package ca.rededaniskal {
    package ca.rededaniskal.Activities {
      package ca.rededaniskal.Activities.Fragments {
        class Search_Fragment {
        }
      }
    }
  }
  

  package ca.rededaniskal {
    package ca.rededaniskal.BusinessLogic {
      class SectionsPageAdapter {
      }
    }
  }
  

  package ca.rededaniskal {
    package ca.rededaniskal.BusinessLogic {
      class SignUpLogic {
      }
    }
  }
  

  package ca.rededaniskal {
    class SignupTest {
    }
  }
  

  package ca.rededaniskal {
    package ca.rededaniskal.Activities {
      class Signup_Activity {
      }
    }
  }
  

  package ca.rededaniskal {
    package ca.rededaniskal.EntityClasses {
      class Text_Post {
      }
    }
  }
  

  package ca.rededaniskal {
    package ca.rededaniskal.EntityClasses {
      class User {
      }
    }
  }
  

  package ca.rededaniskal {
    package ca.rededaniskal.BusinessLogic {
      class UserAdapter {
      }
    }
  }
  

  package ca.rededaniskal {
    package ca.rededaniskal.Activities {
      class User_Details_Activity {
      }
    }
  }
  

  package ca.rededaniskal {
    package ca.rededaniskal.Activities {
      class View_All_Books_Activity {
      }
    }
  }
  

  package ca.rededaniskal {
    package ca.rededaniskal.Activities {
      class View_All_Requests_Activity {
      }
    }
  }
  

  package ca.rededaniskal {
    package ca.rededaniskal.Activities {
      class View_All_Users_Activity {
      }
    }
  }
  

  package ca.rededaniskal {
    package ca.rededaniskal.Activities {
      class View_Borrowed_Requested_Activity {
      }
    }
  }
  

  package ca.rededaniskal {
    package ca.rededaniskal.Activities {
      class View_Friends_Activity {
      }
    }
  }
  

  package ca.rededaniskal {
    package ca.rededaniskal.Activities {
      class View_My_Library_Activity {
      }
    }
  }
  

  package ca.rededaniskal {
    package ca.rededaniskal.Activities {
      package ca.rededaniskal.Activities.Fragments {
        class View_Own_Profile_Fragment {
        }
      }
    }
  }
  

  package ca.rededaniskal {
    package ca.rededaniskal.Activities {
      class View_Rating_Post_Activity {
      }
    }
  }
  

  package ca.rededaniskal {
    package ca.rededaniskal.Activities {
      class View_Text_Post_Activity {
      }
    }
  }
  

  AddBookToLibraryTest -up-|> ActivityTestRule
  Add_Book_To_Library_Activity -up-|> AppCompatActivity
  Add_Book_To_Library_Activity o-- AddBookLogic : businessLogic
  AlertTest -up-|> ActivityTestRule
  AllRequestsAdapter -up-|> Adapter
  AllRequestsTest -up-|> ActivityTestRule
  Barcode_Fragment -up-|> BarcodeReaderListener
  Barcode_Fragment -up-|> Fragment
  Barcode_Fragment o-- Barcode_Reader_Fragment : barcodeReader
  Barcode_Graphic -up-|> Graphic
  Barcode_Graphic_Tracker -up-|> Tracker
  Barcode_Graphic_Tracker o-- Barcode_Graphic : mGraphic
  Barcode_Graphic_Tracker o-- BarcodeGraphicTrackerListener : listener
  Barcode_Reader_Activity -up-|> BarcodeReaderListener
  Barcode_Reader_Activity -up-|> AppCompatActivity
  Barcode_Reader_Activity o-- Barcode_Reader_Fragment : mBarcodeReaderFragment
  Barcode_Reader_Fragment -up-|> OnTouchListener
  Barcode_Reader_Fragment -up-|> BarcodeGraphicTrackerListener
  Barcode_Reader_Fragment -up-|> Fragment
  Barcode_Reader_Fragment o-- CameraSource : mCameraSource
  Barcode_Reader_Fragment o-- CameraSourcePreview : mPreview
  Barcode_Reader_Fragment o-- BarcodeReaderListener : mListener
  Barcode_Reader_Fragment o-- Scanner_Overlay : mScanOverlay
  Barcode_Scanner_Activity -up-|> OnClickListener
  Barcode_Scanner_Activity -up-|> BarcodeReaderListener
  Barcode_Scanner_Activity -up-|> AppCompatActivity
  Barcode_Tracker_Factory -up-|> Factory
  Barcode_Tracker_Factory o-- BarcodeGraphicTrackerListener : listener
  Book -up-|> Serializable
  BookAdapter -up-|> Adapter
  BookAdapter o-- Book_List : bookList
  Book_Details_Activity -up-|> AppCompatActivity
  Book_Details_Activity o-- BorrowRequestAdapter : requestAdapter
  Book_Instance -up-|> Serializable
  Book_Instance -up-|> Book
  Book_List -up-|> Serializable
  BorrowRequest -up-|> Request
  BorrowRequestAdapter -up-|> Adapter
  BorrowRequestBookTest -up-|> ActivityTestRule
  CameraSource o-- FrameProcessingRunnable : mFrameProcessor
  CameraSourcePreview -up-|> ViewGroup
  CameraSourcePreview o-- CameraSource : mCameraSource
  CameraSourcePreview o-- GraphicOverlay : mOverlay
  Check_In -up-|> Book_Exchange
  Check_Out -up-|> Book_Exchange
  Data_Provider o-- Book_Instance : book_instance
  Data_Provider o-- Book_List : book_list
  EditBookDetailsTest -up-|> ActivityTestRule
  EditProfileTest -up-|> ActivityTestRule
  Edit_Book_Instance_Activity -up-|> AppCompatActivity
  Edit_Book_Instance_Activity o-- AddBookLogic : businessLogic
  Edit_Profile_Activity -up-|> AppCompatActivity
  Edit_Profile_Activity o-- editUserDetailsDB : db
  FeedTest -up-|> ActivityTestRule
  Forum o-- Post : newPost
  Forum o-- Master_Book : Book
  FriendListTest -up-|> ActivityTestRule
  Friend_Request -up-|> Request
  Get_All_Books_Data o-- Book_List : all_books_data
  GraphicOverlay -up-|> View
  Launcher_Activity -up-|> AppCompatActivity
  LibraryTest -up-|> ActivityTestRule
  Load_ALL_Books_Business o-- Get_All_Books_Data : All
  LoginTest -up-|> ActivityTestRule
  Login_Activity -up-|> AppCompatActivity
  Login_Activity o-- Log_In_Logic : logic
  Login_Activity o-- SignInDB : db
  Main_Activity -up-|> AppCompatActivity
  Main_Activity o-- SectionsPageAdapter : mSectionsPageAdapter
  Master_Book -up-|> Serializable
  Master_Book -up-|> Book
  Notification_Adapter -up-|> Adapter
  Notification_Adapter o-- Notifications_Fragment : fragment
  Notifications_Fragment -up-|> Fragment
  Notifications_Fragment o-- getUserRequestsDB : db
  PostAdapter -up-|> Adapter
  PostAdapter o-- Post_Feed_Fragment : fragment
  Post_Feed_Fragment -up-|> Fragment
  ProfileTest -up-|> ActivityTestRule
  Rating_Post -up-|> Post
  Scanner_Overlay -up-|> ViewGroup
  Search_Activity -up-|> AppCompatActivity
  Search_Fragment -up-|> Fragment
  SectionsPageAdapter -up-|> FragmentPagerAdapter
  SignupTest -up-|> ActivityTestRule
  Signup_Activity -up-|> AppCompatActivity
  Signup_Activity o-- SignUpLogic : businessLogic
  Signup_Activity o-- User : user
  Text_Post -up-|> Post
  User -up-|> Serializable
  User o-- Book_List : ownedBooks
  User o-- Book_List : borrowedBooks
  User o-- Book_List : requestedBooks
  User o-- Master_Book : favBook
  UserAdapter -up-|> Adapter
  UserAdapter o-- User : globalUser
  User_Details_Activity -up-|> AppCompatActivity
  User_Details_Activity o-- User : user_received
  View_All_Books_Activity -up-|> AppCompatActivity
  View_All_Books_Activity o-- BookAdapter : bookAdapter
  View_All_Books_Activity o-- Book_List : BL
  View_All_Requests_Activity -up-|> AppCompatActivity
  View_All_Requests_Activity o-- BorrowRequestAdapter : adapter
  View_All_Requests_Activity o-- getAllUserRequests : db
  View_All_Users_Activity -up-|> AppCompatActivity
  View_All_Users_Activity o-- UserAdapter : userAdapter
  View_Borrowed_Requested_Activity -up-|> AppCompatActivity
  View_Borrowed_Requested_Activity o-- Book_List : BL
  View_Borrowed_Requested_Activity o-- BookAdapter : bookAdapter
  View_Friends_Activity -up-|> AppCompatActivity
  View_Friends_Activity o-- UserAdapter : userAdapter
  View_My_Library_Activity -up-|> AppCompatActivity
  View_My_Library_Activity o-- BookAdapter : bookAdapter
  View_Own_Profile_Fragment -up-|> Fragment
  View_Own_Profile_Fragment o-- currentUserDetailsDB : db
  View_Rating_Post_Activity -up-|> AppCompatActivity
  View_Text_Post_Activity -up-|> AppCompatActivity


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
