@startuml

title __APP's Class Diagram__\n

  package ca.rededaniskal {
    class Book {
    }
  }
  

  package ca.rededaniskal {
    abstract class BookExchange {
    }
  }
  

  package ca.rededaniskal {
    class BookInstance {
    }
  }
  

  package ca.rededaniskal {
    class BookList {
    }
  }
  

  package ca.rededaniskal {
    class BookNotification {
    }
  }
  

  package ca.rededaniskal {
    class BorrowRequest {
    }
  }
  

  package ca.rededaniskal {
    class BuildConfig {
    }
  }
  

  package ca.rededaniskal {
    class CheckIn {
    }
  }
  

  package ca.rededaniskal {
    class CheckOut {
    }
  }
  

  package ca.rededaniskal {
    class ExampleInstrumentedTest {
    }
  }
  

  package ca.rededaniskal {
    class Forum {
    }
  }
  

  package ca.rededaniskal {
    class FriendNotification {
    }
  }
  

  package ca.rededaniskal {
    class FriendRequest {
    }
  }
  

  package ca.rededaniskal {
    class MainActivity {
    }
  }
  

  package ca.rededaniskal {
    class MasterBook {
    }
  }
  

  package ca.rededaniskal {
    class Notification {
    }
  }
  

  package ca.rededaniskal {
    class Post {
    }
  }
  

  package ca.rededaniskal {
    class Request {
    }
  }
  

  package ca.rededaniskal {
    class User {
    }
  }
  

  BookInstance -up-|> Book
  BookNotification -up-|> Notification
  BorrowRequest -up-|> Request
  CheckIn -up-|> BookExchange
  CheckOut -up-|> BookExchange
  FriendNotification -up-|> Notification
  FriendRequest -up-|> Request
  MainActivity -up-|> AppCompatActivity
  MasterBook -up-|> Book
  Notification o-- Request : request
  User o-- BookList : ownedBooks
  User o-- BookList : borrowedBooks
  User o-- BookList : requestedBooks
  User o-- MasterBook : favBook


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
