@startuml

title __CAMERA's Class Diagram__\n

  package ca.rededaniskal {
    package ca.rededaniskal.Barcode {
      package ca.rededaniskal.Barcode.camera {
        class CameraSource {
            {static} + CAMERA_FACING_BACK : int
            {static} + CAMERA_FACING_FRONT : int
            {static} - TAG : String
            {static} - DUMMY_TEXTURE_NAME : int
            {static} - ASPECT_RATIO_TOLERANCE : float
            - mContext : Context
            - mCameraLock : Object
            - mCamera : Camera
            - mFacing : int
            - mRotation : int
            - mPreviewSize : Size
            - mRequestedFps : float
            - mRequestedPreviewWidth : int
            - mRequestedPreviewHeight : int
            - mFocusMode : String
            - mFlashMode : String
            - mDummySurfaceView : SurfaceView
            - mDummySurfaceTexture : SurfaceTexture
            - mProcessingThread : Thread
            - mBytesToByteBuffer : Map<byte[], ByteBuffer>
            + release()
            + start()
            + start()
            + stop()
            + getPreviewSize()
            + getCameraFacing()
            + doZoom()
            + takePicture()
            + getFocusMode()
            + setFocusMode()
            + getFlashMode()
            + setFlashMode()
            + autoFocus()
            + cancelAutoFocus()
            + setAutoFocusMoveCallback()
            - CameraSource()
            - createCamera()
            {static} - getIdForRequestedCamera()
            {static} - selectSizePair()
            {static} - generateValidPreviewSizeList()
            - selectPreviewFpsRange()
            - setRotation()
            - createPreviewBuffer()
        }
      }
    }
  }
  

  package ca.rededaniskal {
    package ca.rededaniskal.Barcode {
      package ca.rededaniskal.Barcode.camera {
        interface FocusMode {
        }
      }
    }
  }
  

  package ca.rededaniskal {
    package ca.rededaniskal.Barcode {
      package ca.rededaniskal.Barcode.camera {
        interface FlashMode {
        }
      }
    }
  }
  

  package ca.rededaniskal {
    package ca.rededaniskal.Barcode {
      package ca.rededaniskal.Barcode.camera {
        class Builder {
            - mDetector : Detector<?>
            + Builder()
            + setRequestedFps()
            + setFocusMode()
            + setFlashMode()
            + setRequestedPreviewSize()
            + setFacing()
            + build()
        }
      }
    }
  }
  

  package ca.rededaniskal {
    package ca.rededaniskal.Barcode {
      package ca.rededaniskal.Barcode.camera {
        interface ShutterCallback {
            {abstract} + onShutter()
        }
      }
    }
  }
  

  package ca.rededaniskal {
    package ca.rededaniskal.Barcode {
      package ca.rededaniskal.Barcode.camera {
        interface PictureCallback {
            {abstract} + onPictureTaken()
        }
      }
    }
  }
  

  package ca.rededaniskal {
    package ca.rededaniskal.Barcode {
      package ca.rededaniskal.Barcode.camera {
        interface AutoFocusCallback {
            {abstract} + onAutoFocus()
        }
      }
    }
  }
  

  package ca.rededaniskal {
    package ca.rededaniskal.Barcode {
      package ca.rededaniskal.Barcode.camera {
        interface AutoFocusMoveCallback {
            {abstract} + onAutoFocusMoving()
        }
      }
    }
  }
  

  package ca.rededaniskal {
    package ca.rededaniskal.Barcode {
      package ca.rededaniskal.Barcode.camera {
        class PictureStartCallback {
            + onShutter()
        }
      }
    }
  }
  

  package ca.rededaniskal {
    package ca.rededaniskal.Barcode {
      package ca.rededaniskal.Barcode.camera {
        class PictureDoneCallback {
            + onPictureTaken()
        }
      }
    }
  }
  

  package ca.rededaniskal {
    package ca.rededaniskal.Barcode {
      package ca.rededaniskal.Barcode.camera {
        class CameraAutoFocusCallback {
            + onAutoFocus()
        }
      }
    }
  }
  

  package ca.rededaniskal {
    package ca.rededaniskal.Barcode {
      package ca.rededaniskal.Barcode.camera {
        class CameraAutoFocusMoveCallback {
            + onAutoFocusMoving()
        }
      }
    }
  }
  

  package ca.rededaniskal {
    package ca.rededaniskal.Barcode {
      package ca.rededaniskal.Barcode.camera {
        class SizePair {
            - mPreview : Size
            - mPicture : Size
            + SizePair()
            + previewSize()
            + pictureSize()
        }
      }
    }
  }
  

  package ca.rededaniskal {
    package ca.rededaniskal.Barcode {
      package ca.rededaniskal.Barcode.camera {
        class CameraPreviewCallback {
            + onPreviewFrame()
        }
      }
    }
  }
  

  package ca.rededaniskal {
    package ca.rededaniskal.Barcode {
      package ca.rededaniskal.Barcode.camera {
        class FrameProcessingRunnable {
            - mDetector : Detector<?>
            - mStartTimeMillis : long
            - mLock : Object
            - mActive : boolean
            - mPendingTimeMillis : long
            - mPendingFrameId : int
            - mPendingFrameData : ByteBuffer
            ~ FrameProcessingRunnable()
            ~ release()
            ~ setActive()
            ~ setNextFrame()
            + run()
        }
      }
    }
  }
  

  package ca.rededaniskal {
    package ca.rededaniskal.Barcode {
      package ca.rededaniskal.Barcode.camera {
        class CameraSourcePreview {
            {static} - TAG : String
            - mContext : Context
            - mSurfaceView : SurfaceView
            - mStartRequested : boolean
            - mSurfaceAvailable : boolean
            + CameraSourcePreview()
            + start()
            + start()
            + stop()
            + release()
            + setFlash()
            - startIfReady()
            # onLayout()
            - isPortraitMode()
        }
      }
    }
  }
  

  package ca.rededaniskal {
    package ca.rededaniskal.Barcode {
      package ca.rededaniskal.Barcode.camera {
        class SurfaceCallback {
            + surfaceCreated()
            + surfaceDestroyed()
            + surfaceChanged()
        }
      }
    }
  }
  

  package ca.rededaniskal {
    package ca.rededaniskal.Barcode {
      package ca.rededaniskal.Barcode.camera {
        class GraphicOverlay {
            - mLock : Object
            - mPreviewWidth : int
            - mWidthScaleFactor : float
            - mPreviewHeight : int
            - mHeightScaleFactor : float
            - mFacing : int
            - mGraphics : Set<T>
            + GraphicOverlay()
            + clear()
            + add()
            + remove()
            + getGraphics()
            + getWidthScaleFactor()
            + getHeightScaleFactor()
            + setCameraInfo()
            # onDraw()
        }
      }
    }
  }
  

  package ca.rededaniskal {
    package ca.rededaniskal.Barcode {
      package ca.rededaniskal.Barcode.camera {
        abstract class Graphic {
            + Graphic()
            {abstract} + draw()
            + scaleX()
            + scaleY()
            + translateX()
            + translateY()
            + postInvalidate()
        }
      }
    }
  }
  

  CameraSource o-- FrameProcessingRunnable : mFrameProcessor
  CameraSource +-down- FocusMode
  CameraSource +-down- FlashMode
  CameraSource +-down- Builder
  CameraSource +-down- ShutterCallback
  CameraSource +-down- PictureCallback
  CameraSource +-down- AutoFocusCallback
  CameraSource +-down- AutoFocusMoveCallback
  CameraSource +-down- PictureStartCallback
  CameraSource +-down- PictureDoneCallback
  CameraSource +-down- CameraAutoFocusCallback
  CameraSource +-down- CameraAutoFocusMoveCallback
  CameraSource +-down- SizePair
  CameraSource +-down- CameraPreviewCallback
  CameraSource +-down- FrameProcessingRunnable
  Builder o-- CameraSource : mCameraSource
  PictureStartCallback -up-|> ShutterCallback
  PictureStartCallback o-- ShutterCallback : mDelegate
  PictureDoneCallback -up-|> PictureCallback
  PictureDoneCallback o-- PictureCallback : mDelegate
  CameraAutoFocusCallback -up-|> AutoFocusCallback
  CameraAutoFocusCallback o-- AutoFocusCallback : mDelegate
  CameraAutoFocusMoveCallback -up-|> AutoFocusMoveCallback
  CameraAutoFocusMoveCallback o-- AutoFocusMoveCallback : mDelegate
  CameraPreviewCallback -up-|> PreviewCallback
  FrameProcessingRunnable -up-|> Runnable
  CameraSourcePreview -up-|> ViewGroup
  CameraSourcePreview o-- CameraSource : mCameraSource
  CameraSourcePreview o-- GraphicOverlay : mOverlay
  CameraSourcePreview +-down- SurfaceCallback
  SurfaceCallback -up-|> Callback
  MarginLayoutParams -up-|> LayoutParams
  BaseSavedState -up-|> AbsSavedState
  GraphicOverlay -up-|> View
  GraphicOverlay +-down- Graphic
  Graphic o-- GraphicOverlay : mOverlay
  BaseSavedState -up-|> AbsSavedState


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
